stages:
  - build
  - test

build:
  stage: build
  image: node:8
  cache: # Speed up builds
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm install -g truffle
    - yarn install
    - truffle compile
    - yarn run build

test:
  stage: test
  image: node:8
  cache: # Speed up builds
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  before_script:
    - npm install -g ganache-cli
    - npm install -g truffle
    - ganache-cli -p 7545 > /dev/null &
    - sleep 1s
  script:
    - truffle compile
    - truffle migrate --reset
    - yarn run test
