stages:
    - build
    - test

build:
    stage: build
    image: node:8-alpine
    cache: # Speed up builds
        key: $CI_COMMIT_REF_NAME
        paths:
            - vendor
            - node_modules
    script:
        - npm install -g truffle
        - npm install -g ganache-cli
        - yarn install
        - ganache-cli -p 7545
        - truffle compile
        - truffle migrate
        - yarn run build
