stages:
  - build
  - test

build:
  stage: build
  image: node:8
  cache: # Speed up builds
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm install -g truffle
    - yarn install
    - truffle compile
    - yarn run build

test-migrate:
  stage: test
  image: node:8
  cache: # Speed up builds
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  before_script:
    - npm install -g ganache-cli
    - npm install -g truffle
    - ganache-cli -p 7545 &
  script:
    - truffle migrate --reset
  after_script:
    # when a test fails - try to kill it in the after_script. this looks rather complicated, but it makes sure your builds dont fail when the tests succeedes and the lite-server is already killed. to have a successfull build we ensure a non-error return code (exit 0)
    - /bin/bash -c '/usr/bin/killall -q ganache-cli; exit 0'

#test-truffle:
#  stage: test
#  image: node:8
#  cache: # Speed up builds
#    key: $CI_COMMIT_REF_NAME
#    paths:
#      - node_modules
#  script:
#    - npm install -g ganache-cli
#    - ganache-cli -p 7545 &
#    - yarn run test/truffle
#
#test-dapp:
#  stage: test
#  image: node:8
#  cache: # Speed up builds
#    key: $CI_COMMIT_REF_NAME
#    paths:
#      - node_modules
#  script:
#    - npm install -g ganache-cli
#    - ganache-cli -p 7545 &
#    - yarn run test/dapp
