stages:
  - build
  - test

build:
  stage: build
  image: fatesmartcontract/gitlab-ci-truffle-build
  cache: # Speed up builds
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - yarn install
    - truffle compile
    - yarn run build

test:
  stage: test
  image: fatesmartcontract/gitlab-ci-truffle-test
  cache: # Speed up builds
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  before_script:
    - ganache-cli -p 7545 > /dev/null &
    - export DISPLAY=:99
    - export DBUS_SESSION_BUS_ADDRESS=/dev/null
    - Xvfb :99 -ac -shmem -screen 0 1600x1200x16 2>/dev/null 1>&2 &
    - sleep 1s
  script:
    - yarn install
    - truffle compile
    - truffle migrate --reset
    - yarn run test
